name: YOUR APP ID
version: 1

libraries:
- name: bottle
  version: "0.12.9"

handlers:
- compress: if (out_header["Content-Length"]>=128) compress
- compress: if (out_header["Content-type"]=="text/css") compress
- compress: if (out_header["Content-type"]=="text/javascript") compress
- compress: if (out_header["Content-type"]=="text/html") compress
- compress: if (out_header["Content-type"]=="image/png") compress
- compress: if (out_header["Content-type"]=="image/jpeg") compress
- compress: if (out_header["Content-type"]=="text/plain") compress
- compress: if (out_header["Use-Compress"]=="1") compress

handlers:
- url: /robots.txt
  static_path: robots.txt

- url: /favicon.ico
  static_path: favicon.ico
